site_name: Viper 2
repo_url: https://github.com/viper-framework/viper2
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 Claudio Guarnieri
site_description: Viper 2 Documentation
markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        use_pygments: true
theme:
    name: material
    features:
        - tabs
plugins:
    - search
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/botherder
        - icon: fontawesome/brands/mastodon
          link: https://mastodon.social/@botherder
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/botherder
nav:
    - Welcome: "index.md"
